### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LackyPal** [Dev-CasperTheGhost/ctgs.xyz#2]
**An options to login** using email password. So that we can later edit the url.

An option to add a `theme colour`, `og:description`, `og:title` for that short url.

Some **analytics features** to keep track how many times the link has been clicked

**Comment by casperiv0** [comment]
Yeah, sure! This is possible! Will start working on this tomorrow

**Comment by casperiv0** [comment]
@L0SER8228, You can view progress in #3

**Comment by casperiv0** [comment]
A first version of this will be released very soon. This includes login with GitHub, simple analytics, user settings, and profiles. The ability to change urls will come later today/tomorrow!

**Comment by casperiv0** [comment]
Fully finished now, feel free to open another issue with feedback/issues!
